<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Terrain;
use Illuminate\Support\Facades\DB;

class TerrainSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $terrains = [
            [
                'name' => 'Stade Municipal de Casablanca',
                'proprietaire_id' => 2,
                'capacity' => 120,
                'price' => 450.00,
                'status' => 'en_attente',
                'admin_approval' => 'en_attente',
                'reservation_count' => 34,
                'description' => 'Terrain de football professionnel situé au cœur de Casablanca avec d\'excellentes installations.',
                'payment_method' => 'les_deux',
                'surface' => 'gazon_naturel',
                'city' => 'Casablanca',
                'adress' => 'Boulevard Mohammed V, Quartier Anfa',
                'latitude' => 33.5731104,
                'longitude' => -7.6425711,
                'contact' => '0522123456',
            ],
            [
                'name' => 'Terrain El Jadida',
                'proprietaire_id' => 2,
                'capacity' => 80,
                'price' => 350.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 28,
                'description' => 'Terrain synthétique idéal pour les matchs à 7 joueurs, situé près de la plage.',
                'payment_method' => 'sur_place',
                'surface' => 'gazon_synthetique',
                'city' => 'El Jadida',
                'adress' => 'Avenue de la Plage, Quartier El Menzeh',
                'latitude' => 33.2568123,
                'longitude' => -8.5028615,
                'contact' => '0523456789',
            ],
            [
                'name' => 'Complexe Sportif Rabat',
                'proprietaire_id' => 5,
                'capacity' => 150,
                'price' => 550.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 42,
                'description' => 'Grand complexe sportif avec plusieurs terrains, vestiaires modernes et cafétéria.',
                'payment_method' => 'en_ligne',
                'surface' => 'gazon_hybride',
                'city' => 'Rabat',
                'adress' => 'Rue Hassan II, Agdal',
                'latitude' => 34.0081782,
                'longitude' => -6.8406286,
                'contact' => '0537987654',
            ],
            [
                'name' => 'Stade Tanger Indoor',
                'proprietaire_id' => 5,
                'capacity' => 100,
                'price' => 480.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 15,
                'description' => 'Terrain indoor climatisé disponible toute l\'année, même en saison pluvieuse.',
                'payment_method' => 'les_deux',
                'surface' => 'indoor_synthetique',
                'city' => 'Tanger',
                'adress' => 'Zone Industrielle, Route de Tétouan',
                'latitude' => 35.7595068,
                'longitude' => -5.8340213,
                'contact' => '0539123456',
            ],
            [
                'name' => 'Terrain Marrakech Palm',
                'proprietaire_id' => 2,
                'capacity' => 70,
                'price' => 420.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 31,
                'description' => 'Terrain bien entretenu avec vue sur les montagnes de l\'Atlas, idéal pour les matchs amicaux.',
                'payment_method' => 'sur_place',
                'surface' => 'gazon_naturel',
                'city' => 'Marrakech',
                'adress' => 'Route de l\'Ourika, Quartier Palmeraie',
                'latitude' => 31.6294723,
                'longitude' => -7.9810845,
                'contact' => '0524567890',
            ],
            [
                'name' => 'Complexe Sportif Agadir',
                'proprietaire_id' => 5,
                'capacity' => 90,
                'price' => 380.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 23,
                'description' => 'Terrain de football à proximité de la plage avec un beau gazon synthétique et éclairage nocturne.',
                'payment_method' => 'les_deux',
                'surface' => 'gazon_synthetique',
                'city' => 'Agadir',
                'adress' => 'Boulevard du 20 Août, Quartier Talborjt',
                'latitude' => 30.4277547,
                'longitude' => -9.5981072,
                'contact' => '0528789012',
            ],
            [
                'name' => 'Terrain Elite Fès',
                'proprietaire_id' => 2,
                'capacity' => 110,
                'price' => 490.00,
                'status' => 'occupé',
                'admin_approval' => 'approuve',
                'reservation_count' => 37,
                'description' => 'Terrain premium avec installations haut de gamme, incluant vestiaires avec douches et salle de repos.',
                'payment_method' => 'en_ligne',
                'surface' => 'altra_resist',
                'city' => 'Fès',
                'adress' => 'Avenue Hassan II, Quartier Atlas',
                'latitude' => 34.0345932,
                'longitude' => -5.0163239,
                'contact' => '0535234567',
            ],
            [
                'name' => 'Mini Foot Meknès',
                'proprietaire_id' => 5,
                'capacity' => 60,
                'price' => 300.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 19,
                'description' => 'Petit terrain idéal pour les matchs à 5, parfait pour les débutants et les enfants.',
                'payment_method' => 'sur_place',
                'surface' => 'turf_artificiel',
                'city' => 'Meknès',
                'adress' => 'Rue Ibn Sina, Hamria',
                'latitude' => 33.8969422,
                'longitude' => -5.5473648,
                'contact' => '0535678901',
            ],
            [
                'name' => 'Stade Oujda Central',
                'proprietaire_id' => 2,
                'capacity' => 130,
                'price' => 520.00,
                'status' => 'maintenance',
                'admin_approval' => 'approuve',
                'reservation_count' => 8,
                'description' => 'Grand terrain rénové récemment avec pelouse de qualité internationale et tribunes pour spectateurs.',
                'payment_method' => 'les_deux',
                'surface' => 'gazon_hybride',
                'city' => 'Oujda',
                'adress' => 'Boulevard Mohammed VI, Centre Ville',
                'latitude' => 34.6800146,
                'longitude' => -1.9136422,
                'contact' => '0536345678',
            ],
            [
                'name' => 'Terrain Beach Essaouira',
                'proprietaire_id' => 5,
                'capacity' => 50,
                'price' => 280.00,
                'status' => 'disponible',
                'admin_approval' => 'approuve',
                'reservation_count' => 14,
                'description' => 'Terrain de beach soccer unique situé directement sur la plage, idéal pour les tournois d\'été.',
                'payment_method' => 'sur_place',
                'surface' => 'sable',
                'city' => 'Essaouira',
                'adress' => 'Plage de Sidi Kaouki',
                'latitude' => 31.3541262,
                'longitude' => -9.7979244,
                'contact' => '0524987654',
            ],
        ];

        // Insertion des données dans la table
        foreach ($terrains as $terrain) {
            Terrain::create($terrain);
        }
    }
}